# Generated by Django 6.1.1 on 2026-09-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_claim_claimant_alter_claim_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
